version: '3.7'

services:
  recipe-service:
    container_name: recipe-service
    build:
      context: ./recipe-service
      target: development # or test or production
    volumes:
      - ./recipe-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - ./recipe-service/.env
    environment:
      - RECIPES_DB_HOST=recipe-service-pg
      - ADDRESS=0.0.0.0
    networks:
      - recipe-net
    depends_on:
      - recipe-service-pg

  recipe-service-pg:
    container_name: recipe-service-pg
    image: postgres:10.7
    networks:
      - recipe-net
    environment:
      POSTGRES_PASSWORD: ${RECIPES_DB_PASSWORD}
      POSTGRES_USER: ${RECIPES_DB_USERNAME}
      POSTGRES_DB: ${RECIPES_DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - recipe-service-pgdata:/var/lib/postgresql/data

networks:
  recipe-net:
volumes:
  recipe-service-pgdata:
